### ISSUE TITLE
Automatic download of .bdic files not working => workaround

### ISSUE THREAD

**Issue by Bergruebe** [ValentinSchmitz/spell-checker#3]
Hey,
somehow the automatic download and creation of .bdic files didn't worked for me. Maybe it is because I'm using a Mac.
But I found a workaround and maybe this way can be helpful for others too.

My solution is that you can download the '.bdic' files for your language from [this repo](https://github.com/cvsuser-chromium/third_party_hunspell_dictionaries) and put the files into the `.bdic folder`.

Hopefully that helps.

**Comment by ValentinSchmitz** [comment]
Thank you for linking the repo. The plugin does sadly not support macOS right now, because I am currently unable to compile the .bdic converter on macOS. However, as you noted, you can manually add .bdic files and still use the plugin this way, although without the personal dictionary.  The steps to add custom bdic files are outlined [here].(https://github.com/ValentinSchmitz/spell-checker#bdic-files).
